### ISSUE TITLE
Infografia INGENIERIA DE REQUISITOS

### ISSUE THREAD

**Issue by Graciela2000** [SistemasTecTlaxiaco/infografia-Graciela2000#2]
![Ingenieria de requisitos(infografia)](https://user-images.githubusercontent.com/77760362/110015580-a311a980-7ce9-11eb-9e5b-c114e29c8168.jpg)

**Comment by Brendalp** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
